Traceback (most recent call last):
  File "/Users/moh/micromamba/envs/mom1env/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/moh/micromamba/envs/mom1env/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/moh/micromamba/envs/mom1env/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/moh/micromamba/envs/mom1env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/moh/micromamba/envs/mom1env/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/moh/micromamba/envs/mom1env/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/moh/micromamba/envs/mom1env/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
q = QuantumRegister(3, 'q')
c = ClassicalRegister(1, 'c')
qft = QuantumCircuit(q, c)
qft.h(q[0])
qft.cu1(Ï€/2, q[1], q[0])
qft.h(q[1])
qft.cu1(Ï€/4, q[2], q[0])
qft.cu1(Ï€/2, q[2], q[1])
qft.h(q[2])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      3[0m qft [38;5;241m=[39m QuantumCircuit(q, c)
[1;32m      4[0m qft[38;5;241m.[39mh(q[[38;5;241m0[39m])
[0;32m----> 5[0m [43mqft[49m[38;5;241;43m.[39;49m[43mcu1[49m(Ï€[38;5;241m/[39m[38;5;241m2[39m, q[[38;5;241m1[39m], q[[38;5;241m0[39m])
[1;32m      6[0m qft[38;5;241m.[39mh(q[[38;5;241m1[39m])
[1;32m      7[0m qft[38;5;241m.[39mcu1(Ï€[38;5;241m/[39m[38;5;241m4[39m, q[[38;5;241m2[39m], q[[38;5;241m0[39m])

[0;31mAttributeError[0m: 'QuantumCircuit' object has no attribute 'cu1'

